---

- name: Add APT key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /etc/apt/trusted.gpg.d/nodesource.gpg

- name: Add PPA repo
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://deb.nodesource.com/node_6.x {{ os_release_name }} main #NodeSource"
    - "deb-src https://deb.nodesource.com/node_6.x {{ os_release_name }} main #NodeSource (sources)"

- name: Install packages
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - nodejs

- name: Create ~/.npm-global folder
  file:
    path: "{{ home_dir }}/.npm-global"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory

- name: Use ~/.npm-global as NPM prefix
  shell: "npm config set prefix '{{ home_dir }}/.npm-global'"
  become: yes
  become_user: "{{ user_name }}"
