- name: Create ~/.config/profile.d folder
  file:
    path: "{{ home_dir }}/.config/profile.d"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Link ~/.profile
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.profile"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Create ~/.local/bin folder
  file:
    path: "{{ home_dir }}/.local/bin"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Link ~/.config/profile.d/local-bin.sh
  file:
    src: "{{ role_path }}/files/local-bin.sh"
    dest: "{{ home_dir }}/.config/profile.d/local-bin.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
