- name: Install terminator packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - terminator
  become: yes

- name: Create ~/.config/terminator folder
  file:
    path: "{{ home_dir }}/.config/terminator"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Link ~/.config/terminator/config
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ home_dir }}/.config/terminator/config"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
    force: yes
