---
- name: Install Terminator package
  shell: "{{ install_cmd }} {{ item }}"
  with_items:
    - terminator

- name: Create ~/.config/terminator folder
  file:
    path: "{{ home_dir }}/.config/terminator"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Link ~/.config/terminator/config
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ home_dir }}/.config/terminator/config"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
    force: yes
