---
- name: Install Terminator package
  include_role:
    name: system/package
  vars:
    package_names:
      - terminator

- name: Create ~/.config/terminator folder
  file:
    path: "{{ home_dir }}/.config/terminator"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Link ~/.config/terminator/config
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ home_dir }}/.config/terminator/config"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
    force: yes
