---
- name: Install {{ system_package | mandatory }} package
  block:
    - name: Check if rpm-ostree is installed
      stat:
        path: /usr/bin/rpm-ostree
      register: rpm_ostree

    - name: Install {{ system_package | mandatory }} via rpm-ostree
      shell: rpm-ostree install --idempotent --allow-inactive {{ system_package | mandatory }}
      when: rpm_ostree.stat.exists == True

    - name: Install {{ system_package | mandatory }} via default package manager
      package:
        name: "{{ system_package }}"
      when: rpm_ostree.stat.exists == False
