- name: Install packages for fonts management
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mkfontscale
  become: true

- name: Create ~/.local/share/fonts folder
  file:
    path: "{{ home_dir }}/.local/share/fonts"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Install fonts
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/d04875dc8af1a3853aec4e8f0828da9846a7c009/patched-fonts/{{ item.path }}/{{ item.file | urlencode() }}"
    dest: "{{ home_dir }}/.local/share/fonts/{{ item.file }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: "0744"
  with_items:
    - path: "DroidSansMono"
      file: "DroidSansMNerdFontMono-Regular.otf"
    - path: "JetBrainsMono/NoLigatures/Regular"
      file: "JetBrainsMonoNLNerdFontMono-Regular.ttf"
    - path: "SourceCodePro/Regular"
      file: "SauceCodeProNerdFontMono-Regular.ttf"
  notify: "Rebuild fonts cache"
