- name: Install packages for fonts management
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mkfontscale
  become: true

- name: Create ~/.local/share/fonts folder
  file:
    path: "{{ home_dir }}/.local/share/fonts"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Install fonts
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/{{ item.path }}/{{ item.file | urlencode() }}"
    dest: "{{ home_dir }}/.local/share/fonts/{{ item.file }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: "0744"
  with_items:
    - path: "DroidSansMono/complete"
      file: "Droid Sans Mono Nerd Font Complete Mono.otf"
    - path: "SourceCodePro/Regular/complete"
      file: "Sauce Code Pro Nerd Font Complete Mono.ttf"
  notify: "Rebuild fonts cache"
