---
- name: Install OpenJDK packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - java-latest-openjdk-devel

- name: Install Flatpak SDKs
  flatpak:
    name:  org.freedesktop.Sdk.Extension.openjdk8//19.08
    remote: flathub
    method: user
    state: present
  become: no
