- name: Install JDK
  shell: "ln -f -s $(cs java-home --jvm temurin:17 --update) {{home_dir}}/.cache/current-jdk-17"

- name: Link ~/.config/profile.d/java.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/java.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
