- name: Install JDK
  command: "{{ home_dir }}/.local/bin/coursier java-home --jvm openjdk:17 --update"

- name: Link ~/.config/profile.d/java.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/java.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
