---

- name: Check if Vagrant is installed
  shell: "dpkg -s vagrant | grep 'Version: 1:{{ vagrant_version }}'"
  register: vagrant_installed
  ignore_errors: yes

- name: Download package
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/{{ vagrant_deb_name }}"
    dest: "{{ vagrant_deb_tmp }}"
  when: vagrant_installed.rc > 0

- name: Install package
  apt: deb="{{ vagrant_deb_tmp }}"
  when: vagrant_installed.rc > 0

- name: Cleanup
  file:
    path: "{{ vagrant_deb_tmp }}"
    state: absent
  when: vagrant_installed.rc > 0
