---
- name: Add repo
  yum_repository:
    name: vscode
    file: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: yes
    gpgcheck: yes

- name: Install packages
  include_role:
    name: system/package
  vars:
    package_names:
      - code
