---
- hosts: all

  become: yes

  pre_tasks:
    - name: Use default settings file
      set_fact:
        settings_file: settings/settings.yml
      when: settings_file is undefined

    - name: Load settings from "{{ settings_file }}"
      include_vars: "{{ settings_file }}"

  roles:
    - system/profile
    - system/swap
    - system/misc
    - system/config-backup

    - console/profile
    - console/git
    - console/oh-my-zsh
    - console/neovim
    - console/terminator

    - desktop/flatpak
    - desktop/rpmfusion
    - desktop/gnome
    - desktop/apps
    - desktop/vpn

    - dev/base
    - dev/java
    - dev/nodejs
    #- dev/docker
    - dev/vscode
