---

- hosts: all

  become: yes

  pre_tasks:

    - name: Use default settings file
      set_fact:
        settings_file: settings/settings.yml
      when: settings_file is undefined

    - name: Load settings from "{{ settings_file }}"
      include_vars: "{{ settings_file }}"


  roles:

    - basics/profile
    - basics/git
    - basics/oh-my-zsh
    - basics/neovim

    - desktop/sublime-text
    - desktop/skype

    - dev/docker
    - dev/java
    - dev/nodejs
    - dev/vagrant
