- hosts: all

  become: no

  pre_tasks:
    - name: Load settings.yaml
      include_vars: "settings.yaml"

  roles:
    - base/sysctl
    - base/profile
    - base/flatpak
    - base/rpmfusion
    - base/pipx
    - base/nix
    - base/updates

    - console/git
    - console/oh-my-zsh
    - console/nvim
    - console/terminator

    - desktop/gnome-shell
    - desktop/multimedia

    - dev/base
    - dev/coursier
    - dev/go
    - dev/haskell
    - dev/idea
    - dev/java
    - dev/nodejs
    - dev/pgcli
    - dev/podman
    - dev/scala
    - dev/vscodium

    - extra

