---

- name: Install packages
  package: name="{{ item }}" state=latest
  with_items:
    - numix-icon-theme
    - numix-icon-theme-square
    - gnome-shell-extension-windowsNavigator
    # Instead install from extensions.gnome.org via Software + middleclickclose
    #- gnome-shell-extension-dash-to-dock
    #- gnome-shell-extension-topicons-plus
    # Install from COPR `dnf copr enable dmytr/gnome-shell-goodies`
    #- gnome-shell-extension-middle-tap

- name: Configure GNOME
  shell: "dconf load / < {{ role_path }}/files/dconf.ini"
  become: no
