---
- name: Install packages
  include_role:
    name: system/package
  vars:
    package_names:
      - numix-icon-theme
      - numix-icon-theme-square
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-topicons-plus
      - gnome-shell-extension-windowsNavigator

- name: Fix Numix Square icons. Create folders.
  file:
    path: "{{ home_dir }}/.local/share/icons/Numix-Square/48/apps"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Fix Numix Square icons. Link icons.
  file:
    src: "/usr/share/icons/Numix-Square/48/apps/{{ item.from }}"
    dest: "{{ home_dir }}/.local/share/icons/Numix-Square/48/apps/{{ item.to }}"
    state: link
  with_items:
    - from: terminal.svg
      to: terminator.svg
    - from: visualstudiocode.svg
      to: code.svg

- name: Configure GNOME
  shell: "dconf load / < {{ role_path }}/files/dconf.ini"
  become: no

- name: Disable Wayland
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: WaylandEnable
    value: "false"

- name: Make X.org session default
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: DefaultSession
    value: gnome-xorg.desktop

- name: Configure touchpad
  copy:
    src: "{{ role_path }}/files/40-libinput.conf"
    dest: /etc/X11/xorg.conf.d/40-libinput.conf
    owner: "root"
    group: "root"
    mode: "0644"
    force: yes
