---
- name: Install GNOME customiztion packages
  include_role:
    name: helpers/system-package
  vars:
    system_package: "{{ item }}"
  with_items:
    - numix-icon-theme
    - numix-icon-theme-square
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extension-windowsNavigator

- name: Fix Numix Square icons
  block:
    - file:
        path: "{{ home_dir }}/.local/share/icons/Numix-Square/scalable/apps"
        owner: "{{ user_name }}"
        group: "{{ user_group }}"
        state: directory

    - file:
        src: "{{ home_dir }}/.local/share/icons/Numix-Square/scalable"
        dest: "{{ home_dir }}/.local/share/icons/Numix-Square/48"
        owner: "{{ user_name }}"
        group: "{{ user_group }}"
        state: link

    - file:
        src: "{{ home_dir }}/.local/share/icons/Numix-Square"
        dest: "{{ home_dir }}/.local/share/icons/hicolor"
        owner: "{{ user_name }}"
        group: "{{ user_group }}"
        state: link

    - file:
        src: "/usr/share/icons/Numix-Square/48/apps/{{ item.from }}"
        dest: "{{ home_dir }}/.local/share/icons/Numix-Square/scalable/apps/{{ item.to }}"
        state: link
      with_items:
        - from: terminal.svg
          to: terminator.svg
        - from: visualstudiocode.svg
          to: code.svg

- name: Configure GNOME
  shell: "dconf load / < {{ role_path }}/files/dconf.ini"
  become: no

- name: Disable Wayland
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: WaylandEnable
    value: "false"

- name: Make X.org session default
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: DefaultSession
    value: gnome-xorg.desktop

- name: Configure touchpad
  copy:
    src: "{{ role_path }}/files/40-libinput.conf"
    dest: /etc/X11/xorg.conf.d/40-libinput.conf
    owner: "root"
    group: "root"
    mode: "0644"
    force: yes
