- name: Install neovim packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - python3-neovim
    - "@c-development"
  become: yes

- name: Create configuration folders
  file:
    path: "{{ item }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory
  with_items:
    - "{{ home_dir }}/.config"
    - "{{ home_dir }}/.cache/vimfiles/repos/github.com/Shougo"
    - "{{ home_dir }}/.local/share/fonts"

- name: Link spacevim
  file:
    src: "{{ playbook_dir }}/vendor/SpaceVim"
    dest: "{{ home_dir }}/.config/nvim"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Link spacevim configuration files
  file:
    src: "{{ role_path }}/files/spacevim.d"
    dest: "{{ home_dir }}/.config/spacevim.d"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Install plugin manager
  file:
    src: "{{ playbook_dir }}/vendor/dein.vim"
    dest: "{{ home_dir }}/.cache/vimfiles/repos/github.com/Shougo/dein.vim"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Install fonts
  block:
    - name: Find fonts
      find:
        paths:
          - "{{ role_path }}/files/fonts"
        patterns:
          - "*.ttf"
          - "*.otf"
        recurse: no
      register: fonts

    - name: Install fonts
      file:
        src: "{{ role_path }}/files/fonts/{{ item.path | basename }}"
        dest: "{{ home_dir }}/.local/share/fonts/{{ item.path | basename }}"
        owner: "{{ user_name }}"
        group: "{{ user_group }}"
        state: link
      with_items: "{{ fonts.files }}"
      notify: "Rebuild fonts cache"

- name: Link ~/.config/profile.d/spacevim.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/spacevim.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
