- name: Install neovim packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - python3-neovim
    - "@c-development"
    - fd-find
    - ripgrep
  become: true

# TODO: install via NPM globally
# - neovim
# - tree-sitter-cli

- name: Clone a LunarVim repository
  git:
    repo: https://github.com/LunarVim/LunarVim.git
    version: release-1.2/neovim-0.8
    dest: "{{ home_dir }}/.local/share/lunarvim/lvim"

- name: Link ~/.config/lvim
  file:
    src: "{{ role_path }}/files/lvim"
    dest: "{{ home_dir }}/.config/lvim"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Link ~/.config/profile.d/nvim.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/nvim.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
