- name: Install neovim packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - python3-neovim
    - "@c-development"
    - fd-find
    - ripgrep
  become: true

# TODO: install via NPM globally
# - neovim
# - tree-sitter-cli

- name: Link ~/.config/nvim
  file:
    src: "{{ role_path }}/files/lazyvim"
    dest: "{{ home_dir }}/.config/nvim"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Link ~/.config/profile.d/nvim.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/nvim.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
