---

- name: Add APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add PPA repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_release_name }} edge #Docker"

- name: Install packages
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - docker-ce

- name: Add user "{{ user_name }}" to group "docker"
  user:
    name: "{{ user_name }}"
    groups: "docker"
    append: yes
