---

- name: Add APT key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x58118E89F3A912897C070ADBF76221572C52609D
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add PPA repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main #Docker"

- name: Install packages
  apt: name="{{ item }}"
  with_items:
    - docker-engine

- name: Add user "{{ user_name }}" to group "docker"
  user:
    name: "{{ user_name }}"
    groups: "docker"
    append: yes
