---
- name: Install packages
  include_role:
    name: system/package
  vars:
    package_names:
      - flatpak

- name: Add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: no
