---
- name: Install flatpak packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - flatpak

- name: Add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: no
