---
- name: Install packages
  shell: "{{ install_cmd }} {{ item }}"
  with_items:
    - flatpak

- name: Add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: no
