- name: Download GHCup binary
  get_url:
    url: "https://downloads.haskell.org/~ghcup/0.1.17.8/x86_64-linux-ghcup-0.1.17.8"
    checksum: "sha256:d7c66d2c4762393b752634bd4a2d7deb4e22340a9d8af7bb95aa1ce6f6651235"
    dest: "{{ home_dir }}/.local/bin/ghcup"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: "0744"

- name: Install commonly used native libraries
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gmp
    - gmp-devel
    - gmp-devel
    - make
    - ncurses
    - ncurses-compat-libs
    - ncurses-devel
    - ncurses-libs
    - pcre-devel
    - perl
    - xz
    - zlib-devel
  become: true

- name: Link ~/.config/profile.d/haskell.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/haskell.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
