- name: Download stack binary
  get_url:
    url: "https://github.com/commercialhaskell/stack/releases/download/v2.7.3/stack-2.7.3-linux-x86_64-static.tar.gz"
    checksum: "sha256:c5bce24defa2b2b86f1bbb14bed4f1ee83bec14c6ed9fcc81174d5473fbf3450"
    dest: "{{ home_dir }}/.local/bin/stack"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: "0744"

- name: Install commonly used native libraries
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ncurses-libs
    - ncurses-devel
    - pcre-devel
    - gmp-devel
    - zlib-devel
  become: yes
