---
- name: Install stack
  get_url:
    url: "https://github.com/commercialhaskell/stack/releases/download/v2.3.1/stack-2.3.1-linux-x86_64-static-bin"
    dest: "{{ home_dir }}/.local/bin/stack"
    mode: "0755"
  become: no

- name: Upgrade stack
  shell: "{{ home_dir }}/.local/bin/stack upgrade"

- name: Install commonly used native packages
  package: "{{ item }}"
  with_items:
    - pcre-devel
    - gmp-devel
    - zlib-devel

- name: Fix libtinfo
  file:
    src: "/lib64/libtinfo.so.6"
    dest: "/lib64/libtinfo.so.5"
    state: link
