---
- name: Install stack
  include_role:
    name: helpers/package-archive
  vars:
    package_archive:
      name: stack
      archive: "https://get.haskellstack.org/stable/linux-x86_64-static.tar.gz"
      executables:
        - src: stack
          dest: stack

- name: Install commonly used native packages
  include_role:
    name: helpers/system-package
  vars:
    system_package: "{{ item }}"
  with_items:
    - pcre-devel
    - gmp-devel
    - zlib-devel

- name: Fix libtinfo
  file:
    src: "/lib64/libtinfo.so.6"
    dest: "/lib64/libtinfo.so.5"
    state: link
