- name: Download stack binary
  get_url:
    url: "https://github.com/commercialhaskell/stack/releases/download/v2.5.1/stack-2.5.1-linux-x86_64-bin"
    checksum: "sha256:909b7cdff1242274336c4c93101ba835733292b2ebff51e1a1b4bd8b7ba3e2b1"
    dest: "{{ home_dir }}/.local/bin/stack"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: "0744"

- name: Install commonly used native libraries
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ncurses-libs
    - ncurses-devel
    - pcre-devel
    - gmp-devel
    - zlib-devel
  become: yes
