---

- name: Install Terminator package
  package: name="{{ item }}" state=latest
  with_items:
    - terminator

- name: Create ~/.config/terminator folder
  file:
    path: "{{ home_dir }}/.config/terminator"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory

- name: Link ~/.config/terminator/config
  file:
    src: "{{ installation_dir }}/roles/basics/terminator/files/config"
    dest: "{{ home_dir }}/.config/terminator/config"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
    force: yes

