---
# Shell command used to install packages. Package name should be the last argument.
# For Fedora use:
#   install_cmd: dnf install --assumeyes
# For Fedora Silverblue use:
#   install_cmd: rpm-ostree install --idempotent --allow-inactive
install_cmd: "?"

user_name: "?"
user_group: "{{ user_name }}"
home_dir: "/home/{{ user_name }}"

git_name_personal: "?"
git_email_personal: "?"
git_gpg_key_personal: ""

git_work_workspace: ""
git_name_work: ""
git_email_work: ""
git_gpg_key_work: ""

git_instead_of:
  - dest: "?"
    repl: "?"
