- name: Install compilers and CLI tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@c-development"
    - patch
    - curl
    - jq
    - htop
    - fzf
  become: true

- name: Install commonly used native libraries
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libffi-devel
    - python3-devel
    - openssl-devel
  become: true
