- name: Install Podman packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - podman
    - podman-compose
  become: yes

- name: Link ~/.config/profile.d/podman.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/podman.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
