---

- name: Install packages
  package: name="{{ item }}" state=latest
  with_items:
    - neovim
    - python2-devel
    - python2-pip
    - python3-devel
    - python3-pip

- name: Remove vi and vim packages
  package: name="{{ item }}" state=absent
  with_items:
    - vi
    - vim

- name: Update alternatives to use NeoVim
  alternatives: name="{{ item }}" link="/usr/bin/{{item }}" path="/usr/bin/nvim"
  with_items:
    - vi
    - vim
    - editor

- name: Create configuration folders
  file:
    path: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Link configuration files
  file:
    src: "{{ role_path }}/files"
    dest: "{{ home_dir }}/.config/nvim"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Install plugins
  shell: "vim +PlugInstall +PlugUpdate +qall"
  become: no
