---

- name: Install dependencies via NPM
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - typescript
    - tslint
    - typescript-formatter
  become: yes
  become_user: "{{ user_name }}"
