---
- name: Install pipx
  block:
    - stat:
        path: "{{ home_dir }}/.local/bin/pipx"
      register: pipx_link
    - pip:
        name: pipx
        virtualenv: "{{ home_dir }}/Applications/pipx"
        virtualenv_command: "/usr/bin/python3 -m venv"
      when: pipx_link.stat.exists == False
    - file:
        src: "{{ home_dir }}/Applications/pipx/bin/pipx"
        dest: "{{ home_dir }}/.local/bin/pipx"
        state: link
      when: pipx_link.stat.exists == False
  become: no

- name: Install dependencies of {{ pipx_package | mandatory }} package
  include_role:
    name: system/package
  vars:
    package_names: "{{ pipx_package_deps | default([]) | list }}"

- name: Install {{ pipx_package }} package via pipx
  shell: "pipx install {{ pipx_package | mandatory }} {% if pipx_package_force == True %} --force {% else %}{% endif %}"
  become: no
