---
- name: Install pipx
  block:
    - stat:
        path: "{{ home_dir }}/.local/bin/pipx"
      register: pipx_link

    - pip:
        name: pipx
        virtualenv: "{{ home_dir }}/Applications/pipx"
        virtualenv_command: "/usr/bin/python3 -m venv"
      when: pipx_link.stat.exists == False

    - file:
        src: "{{ home_dir }}/Applications/pipx/bin/pipx"
        dest: "{{ home_dir }}/.local/bin/pipx"
        state: link
      when: pipx_link.stat.exists == False
  become: no

- name: Install dependencies of {{ pipx_package.name | mandatory }} package
  package: "{{ pipx_package_dep }}"
  with_items: "{{ pipx_package.deps | default([]) | list }}"
  loop_control:
    loop_var: pipx_package_dep

- name: Install {{ pipx_package.name | mandatory }} package via pipx
  shell: "{{ home_dir }}/.local/bin/pipx install {{ pipx_package.name | mandatory }} {% if pipx_package.force | default(False) == True %} --force {% else %}{% endif %}"
  become: no
