- name: Install coursier via Nix
  command: "nix-env -iA nixpkgs.coursier"

- name: Link ~/.config/profile.d/coursier.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/coursier.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
