session_name: update-everything
suppress_history: true
windows:
   - window_name: dnf
     focus: true
     panes:
        - shell_command:
             - sudo dnf update
          focus: true

   - window_name: flatpak
     panes:
        - shell_command:
             - flatpak update --assumeyes

   - window_name: coursier
     panes:
        - shell_command:
             - >
                cs update &&
                ln -f -s $(cs java-home --jvm temurin:11 --update) ~/.cache/current-jdk-11 &&
                ln -f -s $(cs java-home --jvm temurin:17 --update) ~/.cache/current-jdk-17

   - window_name: nix
     panes:
        - shell_command:
             - nix profile upgrade '.*'

   - window_name: pipx
     panes:
        - shell_command:
             - pipx upgrade-all
