- name: Link ~/.config/profile.d/scala.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/scala.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
