---

- name: Make sure that /etc/X11/xorg.conf.d folder exists
  file:
    path: "/etc/X11/xorg.conf.d"
    owner: root
    group: root
    state: directory

- name: Link /etc/X11/xorg.conf.d/20-intel.conf
  file:
    src: "{{ installation_dir }}/roles/os/intel/files/20-intel.conf"
    dest: "/etc/X11/xorg.conf.d/20-intel.conf"
    owner: root
    group: root
    state: link
