- name: Install GNOME Shell packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-windowsNavigator
    - NetworkManager-openvpn-gnome
    - NetworkManager-openconnect-gnome
    - gnome-tweaks
    - dconf
  become: true

- name: Configure GNOME
  shell: "dconf load / < {{ role_path }}/files/dconf.ini"

- name: Configure Numix Square icons
  block:
    - package:
        name: "{{ item }}"
        state: present
      with_items:
        - numix-icon-theme
        - numix-icon-theme-square
      become: true

    - file:
        path: "{{ home_dir }}/.local/share/icons/Numix-Square/scalable/apps"
        owner: "{{ user_name }}"
        group: "{{ user_group }}"
        state: directory

    - file:
        src: "{{ home_dir }}/.local/share/icons/Numix-Square/scalable"
        dest: "{{ home_dir }}/.local/share/icons/Numix-Square/48"
        owner: "{{ user_name }}"
        group: "{{ user_group }}"
        state: link

    - file:
        src: "{{ home_dir }}/.local/share/icons/Numix-Square"
        dest: "{{ home_dir }}/.local/share/icons/hicolor"
        owner: "{{ user_name }}"
        group: "{{ user_group }}"
        state: link

- name: Install runtimes for flatpak apps
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
    method: user
    state: present
  with_items:
    - name: org.gnome.Platform//44
      remote: flathub
    - name: org.gnome.Platform.Compat.i386//44
      remote: flathub
    - name: org.kde.WaylandDecoration.QGnomePlatform-decoration//5.15-22.08
      remote: flathub
    - name: org.kde.WaylandDecoration.QGnomePlatform-decoration//6.4
      remote: flathub

- name: Install flatpak apps
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
    method: user
    state: present
  with_items:
    - name: org.gnome.Extensions
      remote: flathub
    - name: ca.desrt.dconf-editor
      remote: flathub
