alias gti='git'
alias giti='git'

alias gs='git st'
alias gh='git hist'
alias gd='git diff'
alias gu='git up'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias grm='git rebase -i origin/master'
alias gr='git rebase -i'
alias gc='git commit -m'
alias ga='git add'
alias gaa='git add -A'
alias gb='git checkout'
alias gbn='git checkout -b'
alias gba='git bra'
alias gbd='git br -D'
