---

- name: Install packages
  dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm 
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-29.noarch.rpm
    state: present
