- name: Install codecs, drivers, and firmware
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "@multimedia"
    - "@sound-and-video"
    - "intel-media-driver"
    - "libva-intel-driver"
    - "libva-vdpau-driver"
    - "mesa-vdpau-drivers"
    - "mesa-vulkan-drivers"
    - "gstreamer1-plugins-bad-free"
    - "gstreamer1-plugins-bad-free-extras"
    - "gstreamer1-plugins-bad-freeworld"
    - "gstreamer1-plugins-good"
    - "gstreamer1-plugins-good-extras"
    - "gstreamer1-plugins-ugly"
    - "gstreamer1-plugins-ugly-free"
    - "gstreamer1-libav"
    - "gstreamer1-vaapi"
    - "gstreamer1-svt-av1"
    - "gstreamer1-svt-vp9"
    - "uhd-firmware"
  become: yes

- name: Install flatpak multimedia runtimes
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
    method: user
    state: present
  with_items:
    - name: org.freedesktop.Platform.GL.default/x86_64/21.08
      remote: flathub
    - name: org.freedesktop.Platform.VAAPI.Intel/x86_64/21.08
      remote: flathub
    - name: org.freedesktop.Platform.openh264/x86_64/2.0
      remote: flathub
    - name: org.freedesktop.Platform.ffmpeg-full/x86_64/21.08
      remote: flathub
