---
- name: Install Chromium
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - chromium-freeworld
    - intel-media-driver
    - libva-intel-driver
    - libva-intel-hybrid-driver
    - libva-vdpau-driver

- name: Install apps via flatpak
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
    method: user
    state: present
  with_items:
    - name: org.gnome.meld
      remote: flathub
    - name: org.videolan.VLC
      remote: flathub
    - name: com.jetbrains.IntelliJ-IDEA-Community
      remote: flathub
    - name: com.getpostman.Postman
      remote: flathub
    - name: org.gimp.GIMP
      remote: flathub
  become: no

- name: Link custom icons
  file:
    src: "{{ item.from }}"
    dest: "{{ home_dir }}/.local/share/icons/Numix-Square/scalable/apps/{{ item.to }}"
    state: link
  with_items:
    - from: "{{ home_dir }}/.local/share/flatpak/app/com.jetbrains.IntelliJ-IDEA-Community/current/active/export/share/icons/hicolor/scalable/apps/com.jetbrains.IntelliJ-IDEA-Community.svg"
      to: com.jetbrains.IntelliJ-IDEA-Community.svg
    - from: "{{ home_dir }}/.local/share/flatpak/app/com.getpostman.Postman/current/active/export/share/icons/hicolor/scalable/apps/com.getpostman.Postman.svg"
      to: com.getpostman.Postman.svg
    - from: /usr/share/icons/Numix-Square/48/apps//chromium.svg
      to: chromium-freeworld.svg
