- name: Install vscodium via flatpak
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
    method: user
    state: present
  with_items:
    - name: com.vscodium.codium
      remote: flathub

- name: Install additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - fira-code-fonts
    - "@c-development"
  become: true

- name: Link ~/.config/profile.d/vscodium.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/vscodium.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
