- name: Install pgcli dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - libpq-devel
    - python3-devel
  become: true

- name: Install pgcli package via pipx
  command: pipx install --force pgcli
