---
- name: Install Node packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
  become: true

- name: Create ~/.config/npm folder
  file:
    path: "{{ home_dir }}/.config/npm"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Create ~/.local/npm folder
  file:
    path: "{{ home_dir }}/.local/npm"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Link ~/.config/npm/npmrc
  file:
    src: "{{ role_path }}/files/npmrc"
    dest: "{{ home_dir }}/.config/npm/npmrc"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link

- name: Link ~/.config/profile.d/nodejs.sh
  file:
    src: "{{ role_path }}/files/profile.sh"
    dest: "{{ home_dir }}/.config/profile.d/nodejs.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
