---
- name: Install packages
  shell: "{{ install_cmd }} {{ item }}"
  with_items:
    - nodejs

- name: Create ~/.npm-global folder
  file:
    path: "{{ home_dir }}/.npm-global"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: directory

- name: Use ~/.npm-global as NPM prefix
  template:
    src: npmrc
    dest: "{{ home_dir }}/.npmrc"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

- name: Link ~/.config/profile.d/npm-global-bin.sh
  file:
    src: "{{ role_path }}/files/npm-global-bin.sh"
    dest: "{{ home_dir }}/.config/profile.d/npm-global-bin.sh"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    state: link
    force: yes
