---
- name: Install packages from "C Development Tools and Libraries"
  include_role:
    name: helpers/system-package
  vars:
    system_package: "{{ item }}"
  with_items:
    - autoconf
    - automake
    - binutils
    - bison
    - flex
    - gcc
    - gcc-c++
    - gdb
    - glibc-devel
    - libtool
    - make
    - pkgconf
    - strace
    - elfutils

- name: Install useful CLI tools
  include_role:
    name: helpers/system-package
  vars:
    system_package: "{{ item }}"
  with_items:
    - patch
    - curl
    - jq
    - htop

- name: Install packages via pipx
  include_role:
    name: helpers/pipx-package
  vars:
    pipx_package: "{{ item }}"
  with_items:
    - name: pipx
      force: True
    - name: pgcli
      deps:
        - postgresql
        - libpq-devel
        - python3-devel
    - name: podman-compose
      deps:
        - podman
