---

- name: Install packages
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - neovim
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

- name: Update alternatives to use NeoVim
  alternatives: name="{{ item }}" link="/usr/bin/{{item }}" path="/usr/bin/nvim"
  with_items:
    - vi
    - vim
    - editor

- name: Create configuration folders
  file:
    path: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory

- name: Link configuration files
  file:
    src: "{{ installation_dir }}/roles/basics/neovim/files"
    dest: "{{ home_dir }}/.config/nvim"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
