---

- name: Check if Nix is istalled
  command: which nix-env
  register: nix_found
  ignore_errors: true
  become: false

- name: Install Nix
  shell: "{{ installation_dir }}/roles/basics/nix/files/install.sh"
  when: nix_found|failed
  become: false

- name: Create ~/.config/nixpkgs folder
  file:
    path: "{{ home_dir }}/.config/nixpkgs"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory

- name: Link ~/.config/nixpkgs/config.nix
  file:
    src: "{{ installation_dir }}/roles/basics/nix/files/config.nix"
    dest: "{{ home_dir }}/.config/nixpkgs/config.nix"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
    force: yes

- name: Link ~/.config/profile.d/nix-config.sh
  file:
    src: "{{ installation_dir }}/roles/basics/nix/files/nix-config.sh"
    dest: "{{ home_dir }}/.config/profile.d/nix-config.sh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
    force: yes

- name: Link ~/.local/nixpkgs
  file:
    src: "{{ installation_dir }}/vendor/local-nixpkgs"
    dest: "{{ home_dir }}/.local/nixpkgs"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
    force: yes

- name: Create /usr/local/lib/systemd/system folder
  file:
    path: "/usr/local/lib/systemd/system"
    owner: "root"
    group: "root"
    state: directory

- name: Copy /usr/local/lib/systemd/system/nix-opengl.service
  copy:
    src: "{{ installation_dir }}/roles/basics/nix/files/nix-opengl.service"
    dest: "/usr/local/lib/systemd/system/nix-opengl.service"
    owner: "root"
    group: "root"
    force: yes

- name: Start nix-opengl.service
  systemd:
    name: nix-opengl.service
    state: started
    enabled: yes
    daemon_reload: yes

